name: Notion Advent Calendar Action
on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  advent-calender:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true
    steps:
      - run: cat $GITHUB_EVENT_PATH
      - uses: takumma/notion-advent-calendar-action@v1.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}
